/**
 * PDF Generator Service
 * Generates a professional medical summary PDF using PDFKit.
 */

const PDFDocument = require('pdfkit');

function generatePDF(visitData, extractedData, doctorSummary) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50, size: 'A4' });
            const chunks = [];

            doc.on('data', chunk => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', reject);

            // Header
            doc.fontSize(20).font('Helvetica-Bold')
                .text('MedBrief AI', { align: 'center' });
            doc.fontSize(10).font('Helvetica')
                .fillColor('#666')
                .text('AI-Powered Medical Visit Summary', { align: 'center' });
            doc.moveDown(0.5);

            // Divider
            doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#0ea5e9');
            doc.moveDown(0.5);

            // Patient Info
            doc.fontSize(12).fillColor('#000').font('Helvetica-Bold')
                .text('Patient Information');
            doc.fontSize(10).font('Helvetica')
                .text(`Patient: ${extractedData.PatientName || 'Not specified'}`)
                .text(`Date: ${extractedData.Date || visitData.visit_date}`)
                .text(`Visit ID: ${visitData.id || 'N/A'}`);
            doc.moveDown();

            // Sections
            const sections = [
                { title: 'Symptoms', data: extractedData.Symptoms },
                { title: 'Duration', data: extractedData.Duration },
                { title: 'Diagnosis', data: extractedData.Diagnosis },
                { title: 'Tests Advised', data: extractedData.TestsAdvised },
                { title: 'Lifestyle Advice', data: extractedData.LifestyleAdvice },
                { title: 'Red Flags', data: extractedData.RedFlags },
            ];

            sections.forEach(section => {
                if (section.data && section.data.length > 0) {
                    doc.fontSize(11).font('Helvetica-Bold').fillColor('#0369a1')
                        .text(section.title);
                    doc.fontSize(10).font('Helvetica').fillColor('#000');
                    section.data.forEach(item => {
                        doc.text(`  • ${item}`);
                    });
                    doc.moveDown(0.5);
                }
            });

            // Prescriptions table
            if (extractedData.Prescriptions && extractedData.Prescriptions.length > 0) {
                doc.fontSize(11).font('Helvetica-Bold').fillColor('#0369a1')
                    .text('Prescriptions');
                doc.moveDown(0.3);

                extractedData.Prescriptions.forEach((rx, i) => {
                    doc.fontSize(10).font('Helvetica-Bold').fillColor('#000')
                        .text(`  ${i + 1}. ${rx.Medicine} (${rx.Dosage})`);
                    doc.font('Helvetica')
                        .text(`     Frequency: ${rx.Frequency}`)
                        .text(`     Duration: ${rx.Duration}`);
                    doc.moveDown(0.3);
                });
                doc.moveDown(0.5);
            }

            // Follow-up
            doc.fontSize(11).font('Helvetica-Bold').fillColor('#0369a1')
                .text('Follow-Up');
            doc.fontSize(10).font('Helvetica').fillColor('#000')
                .text(`  ${extractedData.FollowUp || 'Not specified'}`);
            doc.moveDown();

            // Confidence
            doc.fontSize(10).fillColor('#666')
                .text(`AI Confidence Score: ${extractedData.ConfidenceScore || 'N/A'}`);
            doc.moveDown();

            // Signature
            if (visitData.doctor_signature) {
                doc.fontSize(11).font('Helvetica-Bold').fillColor('#000')
                    .text('Doctor Signature:');
                doc.moveDown(0.3);
                doc.text('[Digitally Signed]');
                doc.moveDown();
            }

            // Disclaimer
            doc.moveDown();
            doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e11d48');
            doc.moveDown(0.3);
            doc.fontSize(8).fillColor('#e11d48').font('Helvetica-Bold')
                .text('⚕️ DISCLAIMER: This is an AI-generated medical summary. Doctor verification is required before clinical use. This document does not constitute medical advice.', {
                    align: 'center'
                });

            // Footer
            doc.moveDown();
            doc.fontSize(7).fillColor('#999')
                .text(`Generated by MedBrief AI on ${new Date().toLocaleString()}`, { align: 'center' });

            doc.end();
        } catch (err) {
            reject(err);
        }
    });
}

module.exports = { generatePDF };
